kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/drone/go-scm


steps:
- name: test
  image: golang:1.11
  commands:
  - go get github.com/google/go-cmp/cmp
  - go get gopkg.in/h2non/gock.v1
  - go test -cover github.com/drone/go-scm/scm/...
