apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/jenkins-x/lighthouse
    changes:
    - regex:
        pattern: |
          \s+jenkins-x/go-scm v(.*)
        files:
        - "go.mod"
