apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/lighthouse
      changes:
      - go:
          package: github.com/jenkins-x/go-scm